/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyMfaRouteImport } from './routes/verify-mfa'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelRouteImport } from './routes/$model'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelListRouteImport } from './routes/$model/list'
import { Route as ModelIdShowRouteImport } from './routes/$model/$id/show'
import { Route as ModelIdEditRouteImport } from './routes/$model/$id/edit'

const VerifyMfaRoute = VerifyMfaRouteImport.update({
  id: '/verify-mfa',
  path: '/verify-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelListRoute = ModelListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ModelRoute,
} as any)
const ModelIdShowRoute = ModelIdShowRouteImport.update({
  id: '/$id/show',
  path: '/$id/show',
  getParentRoute: () => ModelRoute,
} as any)
const ModelIdEditRoute = ModelIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ModelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$model': typeof ModelRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-mfa': typeof VerifyMfaRoute
  '/$model/list': typeof ModelListRoute
  '/$model/$id/edit': typeof ModelIdEditRoute
  '/$model/$id/show': typeof ModelIdShowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$model': typeof ModelRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-mfa': typeof VerifyMfaRoute
  '/$model/list': typeof ModelListRoute
  '/$model/$id/edit': typeof ModelIdEditRoute
  '/$model/$id/show': typeof ModelIdShowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$model': typeof ModelRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-mfa': typeof VerifyMfaRoute
  '/$model/list': typeof ModelListRoute
  '/$model/$id/edit': typeof ModelIdEditRoute
  '/$model/$id/show': typeof ModelIdShowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$model'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/verify-mfa'
    | '/$model/list'
    | '/$model/$id/edit'
    | '/$model/$id/show'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$model'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/verify-mfa'
    | '/$model/list'
    | '/$model/$id/edit'
    | '/$model/$id/show'
  id:
    | '__root__'
    | '/'
    | '/$model'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/verify-mfa'
    | '/$model/list'
    | '/$model/$id/edit'
    | '/$model/$id/show'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelRoute: typeof ModelRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  VerifyMfaRoute: typeof VerifyMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-mfa': {
      id: '/verify-mfa'
      path: '/verify-mfa'
      fullPath: '/verify-mfa'
      preLoaderRoute: typeof VerifyMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$model': {
      id: '/$model'
      path: '/$model'
      fullPath: '/$model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$model/list': {
      id: '/$model/list'
      path: '/list'
      fullPath: '/$model/list'
      preLoaderRoute: typeof ModelListRouteImport
      parentRoute: typeof ModelRoute
    }
    '/$model/$id/show': {
      id: '/$model/$id/show'
      path: '/$id/show'
      fullPath: '/$model/$id/show'
      preLoaderRoute: typeof ModelIdShowRouteImport
      parentRoute: typeof ModelRoute
    }
    '/$model/$id/edit': {
      id: '/$model/$id/edit'
      path: '/$id/edit'
      fullPath: '/$model/$id/edit'
      preLoaderRoute: typeof ModelIdEditRouteImport
      parentRoute: typeof ModelRoute
    }
  }
}

interface ModelRouteChildren {
  ModelListRoute: typeof ModelListRoute
  ModelIdEditRoute: typeof ModelIdEditRoute
  ModelIdShowRoute: typeof ModelIdShowRoute
}

const ModelRouteChildren: ModelRouteChildren = {
  ModelListRoute: ModelListRoute,
  ModelIdEditRoute: ModelIdEditRoute,
  ModelIdShowRoute: ModelIdShowRoute,
}

const ModelRouteWithChildren = ModelRoute._addFileChildren(ModelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelRoute: ModelRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  VerifyMfaRoute: VerifyMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
